"use strict";

module.exports = {
	CHANGE_EVENT: "CHANGE_EVENT",

	VIEW_ACTION: "VIEW_ACTION",

	UPDATE_CUSTOMERS: "UPDATE_CUSTOMERS",
	UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
	UPDATE_PROPERTIES: "UPDATE_PROPERTIES",
	UPDATE_SUPPLIERS: "UPDATE_SUPPLIERS",

	UPDATE_NOTIFICATIONS: "UPDATE_NOTIFICATIONS",

	USERMENU_MYACCOUNT_LINK: "/user/profile/view",
	USERMENU_MYACCOUNT_TEXT: "My Account",
	USERMENU_LOGOUT_LINK: "/user/logout",
	USERMENU_LOGOUT_TEXT: "Logout"
};