"use strict";

module.exports = {
	CHANGE_EVENT: "CHANGE_EVENT",

	VIEW_ACTION: "VIEW_ACTION",

	UPDATE_SUPPLIERS: "UPDATE_SUPPLIERS",

	PRODUCT_SEARCH_SUPPLIERS: "PRODUCT_SEARCH_SUPPLIERS",
	PRODUCT_SELECT_SUPPLIER: "PRODUCT_SELECT_SUPPLIER"
};