"use strict";

module.exports = {
	CHANGE_EVENT: "CHANGE_EVENT",
	VIEW_ACTION: "VIEW_ACTION",

	UPDATE_QUOTE: "UPDATE_QUOTE",
	ADD_PRODUCT_TO_QUOTE: "ADD_PRODUCT_TO_QUOTE",
	SET_CUSTOMER_ON_QUOTE: "SET_CUSTOMER_ON_QUOTE",
	SET_PRODUCT_QUANTITY_ON_QUOTE: "SET_PRODUCT_QUANTITY_ON_QUOTE",
	SET_PROPERTY_ON_QUOTE: "SET_PROPERTY_ON_QUOTE"
};