module.exports = {
	CHANGE_EVENT:				"CHANGE_EVENT",

	VIEW_ACTION:				"VIEW_ACTION",


	ADD_PRODUCT_TO_ORDER:		"ADD_PRODUCT_TO_ORDER",
	SET_CUSTOMER_ON_ORDER:		"SET_CUSTOMER_ON_ORDER",
	SET_PRODUCT_QUANTITY_ON_ORDER: "SET_PRODUCT_QUANTITY_ON_ORDER",
	SET_PROPERTY_ON_ORDER:		"SET_PROPERTY_ON_ORDER",

	UPDATE_LIST:				"UPDATE_LIST",

	UPDATE_NOTIFICATIONS:		"UPDATE_NOTIFICATIONS",


	UPDATE_CUSTOMERS:			"UPDATE_CUSTOMERS",
	UPDATE_PRODUCTS:			"UPDATE_PRODUCTS",
	UPDATE_PROPERTIES:			"UPDATE_PROPERTIES",
	UPDATE_SUPPLIERS:			"UPDATE_SUPPLIERS"
};
