module.exports = {
	CHANGE_EVENT:				"CHANGE_EVENT",
	VIEW_ACTION:				"VIEW_ACTION",

	UPDATE_CUSTOMER:			"UPDATE_CUSTOMER",
	UPDATE_CUSTOMER_NAME:		"UPDATE_CUSTOMER_NAME",
	UPDATE_CUSTOMER_BILLING_ADDRESS_LINE1: "UPDATE_CUSTOMER_BILLING_ADDRESS_LINE1",
	UPDATE_CUSTOMER_BILLING_ADDRESS_LINE2: "UPDATE_CUSTOMER_BILLING_ADDRESS_LINE1",
	UPDATE_CUSTOMER_BILLING_ADDRESS_LINE3: "UPDATE_CUSTOMER_BILLING_ADDRESS_LINE1",
	UPDATE_CUSTOMER_BILLING_ADDRESS_LINE4: "UPDATE_CUSTOMER_BILLING_ADDRESS_LINE1",
	UPDATE_CUSTOMER_BILLING_ADDRESS_POSTCODE: "UPDATE_CUSTOMER_BILLING_ADDRESS_POSTCODE",
	UPDATE_CUSTOMER_TELEPHONE:	"UPDATE_CUSTOMER_TELEPHONE",
	UPDATE_CUSTOMER_EMAIL:		"UPDATE_CUSTOMER_EMAIL"
};
