module.exports = {
	CHANGE_EVENT:				"CHANGE_EVENT",
	VIEW_ACTION:				"VIEW_ACTION",

	UPDATE_ORDER:				"UPDATE_ORDER",
	ADD_PRODUCT_TO_ORDER:		"ADD_PRODUCT_TO_ORDER",
	SET_CUSTOMER_ON_ORDER:		"SET_CUSTOMER_ON_ORDER",
	SET_PRODUCT_QUANTITY_ON_ORDER:	"SET_PRODUCT_QUANTITY_ON_ORDER",
	SET_PROPERTY_ON_ORDER:		"SET_PROPERTY_ON_ORDER",

	
	SET_DELIVERY_DATE:			"SET_DELIVERY_DATE",
	SET_STATUS:					"SET_STATUS"
};
