module.exports = {
	CHANGE_EVENT:				"CHANGE_EVENT",
	VIEW_ACTION:				"VIEW_ACTION",

	UPDATE_ORDER:				"UPDATE_ORDER",
	ADD_PRODUCT_TO_ORDER:		"ADD_PRODUCT_TO_ORDER",
	SET_CUSTOMER_ON_ORDER:		"SET_CUSTOMER_ON_ORDER",
	SET_PRODUCT_QUANTITY_ON_ORDER:	"SET_PRODUCT_QUANTITY_ON_ORDER",
	SET_PROPERTY_ON_ORDER:		"SET_PROPERTY_ON_ORDER",



	SET_STATUS:								"SET_STATUS",
	SET_DELIVERY_DATE:						"SET_DELIVERY_DATE",
	UPDATE_BILLING_CUSTOMER_NAME:			"UPDATE_BILLING_CUSTOMER_NAME",
	UPDATE_BILLING_COMPANY_NAME:			"UPDATE_BILLING_COMPANY_NAME",
	UPDATE_BILLING_ADDRESS_LINE1:			"UPDATE_BILLING_ADDRESS_LINE1",
	UPDATE_BILLING_ADDRESS_LINE2:			"UPDATE_BILLING_ADDRESS_LINE2",
	UPDATE_BILLING_ADDRESS_LINE3:			"UPDATE_BILLING_ADDRESS_LINE3",
	UPDATE_BILLING_ADDRESS_LINE4:			"UPDATE_BILLING_ADDRESS_LINE4",
	UPDATE_BILLING_ADDRESS_POSTCODE:		"UPDATE_BILLING_ADDRESS_POSTCODE",
	UPDATE_BILLING_EMAIL:					"UPDATE_BILLING_EMAIL",
	UPDATE_BILLING_TELEPHONE:				"UPDATE_BILLING_TELEPHONE",
	UPDATE_DELIVERY_ADDRESS_LINE1:			"UPDATE_DELIVERY_ADDRESS_LINE1",
	UPDATE_DELIVERY_ADDRESS_LINE2:			"UPDATE_DELIVERY_ADDRESS_LINE2",
	UPDATE_DELIVERY_ADDRESS_LINE3:			"UPDATE_DELIVERY_ADDRESS_LINE3",
	UPDATE_DELIVERY_ADDRESS_LINE4:			"UPDATE_DELIVERY_ADDRESS_LINE4",
	UPDATE_DELIVERY_ADDRESS_POSTCODE:		"UPDATE_DELIVERY_ADDRESS_POSTCODE",
	UPDATE_DELIVERY_ACCESS_ARRANGEMENTS:	"UPDATE_DELIVERY_ACCESS_ARRANGEMENTS",
	UPDATE_DELIVERY_TELEPHONE:				"UPDATE_DELIVERY_TELEPHONE",
	SET_PRODUCT_NAME_ON_ORDER:				"SET_PRODUCT_NAME_ON_ORDER",
	SET_SUBTOTAL:							"SET_SUBTOTAL",
	SET_VAT:								"SET_VAT",
	SET_TOTAL:								"SET_TOTAL",

	SET_ORDER_CORRECT:						"SET_ORDER_CORRECT",
	SET_PROPERTY_TIDY:						"SET_PROPERTY_TIDY",
	SET_NOTICE_AGREED:						"SET_NOTICE_AGREED",
	SET_PAYMENT_AGREED:						"SET_PAYMENT_AGREED"
};
