module.exports = {
	CHANGE_EVENT:				"CHANGE_EVENT",
	VIEW_ACTION:				"VIEW_ACTION",

	UPDATE_PRODUCT:				"UPDATE_PRODUCT",
	UPDATE_PRODUCTS:			"UPDATE_PRODUCTS",
	UPDATE_PRODUCT_CODE:		"UPDATE_PRODUCT_CODE",
	UPDATE_PRODUCT_NAME:		"UPDATE_PRODUCT_NAME",
	UPDATE_PRODUCT_TYPE:		"UPDATE_PRODUCT_TYPE",
	SELECT_PRODUCT_SUPPLIER:	"SELECT_PRODUCT_SUPPLIER",
	UPDATE_PRODUCT_PRICE:		"UPDATE_PRODUCT_PRICE"
};
