module.exports = {
	CHANGE_EVENT:				"CHANGE_EVENT",
	VIEW_ACTION:				"VIEW_ACTION",

	UPDATE_PRODUCT_VARIATION:			"UPDATE_PRODUCT_VARIATION",
	UPDATE_PRODUCT_VARIATIONS:			"UPDATE_PRODUCT_VARIATIONS",
	UPDATE_PRODUCT_VARIATION_LABEL:		"UPDATE_PRODUCT_VARIATION_LABEL",
	UPDATE_PRODUCT_VARIATION_NAME:		"UPDATE_PRODUCT_VARIATION_NAME"
};