module.exports = {
	CHANGE_EVENT:				"CHANGE_EVENT",
	VIEW_ACTION:				"VIEW_ACTION",

	UPDATE_PRODUCT_VARIATION_GROUP:			"UPDATE_PRODUCT_VARIATION_GROUP",
	UPDATE_PRODUCT_VARIATION_GROUPS:			"UPDATE_PRODUCT_VARIATION_GROUPS",
	UPDATE_PRODUCT_VARIATION_GROUP_NAME:		"UPDATE_PRODUCT_VARIATION_GROUP_NAME"
};