module.exports = {
	CHANGE_EVENT:							"CHANGE_EVENT",
	VIEW_ACTION:							"VIEW_ACTION",

	UPDATE_PROPERTY:						"UPDATE_PROPERTY",
	UPDATE_PROPERTY_ADDRESS_LINE1:			"UPDATE_PROPERTY_ADDRESS_LINE1",
	UPDATE_PROPERTY_ADDRESS_LINE2:			"UPDATE_PROPERTY_ADDRESS_LINE2",
	UPDATE_PROPERTY_ADDRESS_LINE3:			"UPDATE_PROPERTY_ADDRESS_LINE3",
	UPDATE_PROPERTY_ADDRESS_LINE4:			"UPDATE_PROPERTY_ADDRESS_LINE4",
	UPDATE_PROPERTY_ADDRESS_POSTCODE:		"UPDATE_PROPERTY_ADDRESS_POSTCODE",
	UPDATE_PROPERTY_ACCESS_ARRANGEMENTS:	"UPDATE_PROPERTY_ACCESS_ARRANGEMENTS",
	UPDATE_PROPERTY_TELEPHONE:				"UPDATE_PROPERTY_TELEPHONE"
};
