module.exports = {
	CHANGE_EVENT:				"CHANGE_EVENT",
	VIEW_ACTION:				"VIEW_ACTION",

	UPDATE_SUPPLIER:			"UPDATE_SUPPLIER",
	UPDATE_SUPPLIERS:			"UPDATE_SUPPLIERS",
	UPDATE_SUPPLIER_NAME:		"UPDATE_SUPPLIER_NAME",
	UPDATE_SUPPLIER_BILLING_ADDRESS_LINE1: "UPDATE_SUPPLIER_BILLING_ADDRESS_LINE1",
	UPDATE_SUPPLIER_BILLING_ADDRESS_LINE2: "UPDATE_SUPPLIER_BILLING_ADDRESS_LINE2",
	UPDATE_SUPPLIER_BILLING_ADDRESS_LINE3: "UPDATE_SUPPLIER_BILLING_ADDRESS_LINE3",
	UPDATE_SUPPLIER_BILLING_ADDRESS_LINE4: "UPDATE_SUPPLIER_BILLING_ADDRESS_LINE4",
	UPDATE_SUPPLIER_BILLING_ADDRESS_POSTCODE: "UPDATE_SUPPLIER_BILLING_ADDRESS_POSTCODE",
	UPDATE_SUPPLIER_TELEPHONE:	"UPDATE_SUPPLIER_TELEPHONE",
	UPDATE_SUPPLIER_EMAIL:		"UPDATE_SUPPLIER_EMAIL"
};